pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/beastguhan/one-data-structure.git'
            }
        }

        stage('Install & Test') {
            steps {
                sh '''
                    echo "Installing Python dependencies..."
                    pip install -r assignment/app/requirement.txt --break-system-packages
                    echo "✅ Python dependencies installed successfully!"
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "Building Docker image..."
                    docker build -t flask-app -f assignment/Dockerfile assignment
                    echo "✅ Docker image built successfully!"
                '''
            }
        }

        stage('Run Container Test') {
            steps {
                sh '''
                    echo "Running Docker container for test..."
                    docker run -d --name flask-app-container -p 5000:5000 flask-app
                    sleep 5
                    docker ps
                    echo "✅ Container is up and running!"
                '''
            }
        }
    }

    post {
        always {
            echo "✅ Pipeline Finished"
        }
        failure {
            echo "❌ Build failed!"
        }
    }
}
