pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/beastguhan/one-data-structure.git'
            }
        }

        stage('Install & Test') {
            steps {
                sh '''
                pip install -r requirements.txt
                python -m unittest discover -s tests || echo "No tests folder, skipping..."
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t flask-app .'
            }
        }

        stage('Run Container Test') {
            steps {
                sh '''
                docker rm -f flask-app-container || true
                docker run -d --name flask-app-container -p 5000:5000 flask-app
                sleep 5
                docker ps
                '''
            }
        }
    }

    post {
        always {
            sh 'docker rm -f flask-app-container || true'
            echo "✅ Pipeline Finished"
        }
        failure {
            echo "❌ Build failed!"
        }
    }
}

